version: "3"

services:
  projects:
    build: ./projects
    links:
      - redis-data
    ports:
      - 1337
    volumes:
      - ./projects:/src:rw
  todos:
    build: ./todos
    links:
      - redis-data
      - projects
    ports:
      - 1447
    volumes:
      - ./todos:/src:rw
  client:
    build: ./client
    links:
      - projects
      - todos
    ports:
      - 1557
    volumes:
      - ./client:/src:rw
  reverseproxy:
    build: ./proxy
    links:
      - projects
      - todos
      - client
    ports:
      - 1337:1337
      - 1447:1447
      - 1557:1557
    restart: always
  redis-data:
    image: redis
    ports:
      - 6379