version: "3"

services:
  projects:
    build: ./projects
    links:
      - redis-data
      - file-server
    ports:
      - 1337
    volumes:
      - ./projects:/src:rw
  todos:
    build: ./todos
    links:
      - redis-data
      - file-server
    ports:
      - 1447
    volumes:
      - ./todos:/src:rw
  client:
    build: ./client
    links:
      - projects
      - todos
      - file-server
    ports:
      - 1557
    volumes:
      - ./client:/src:rw
  file-server:
    build: ./file-server
    ports:
      - 1667
    volumes:
      - ./file-server:/src:rw
  reverseproxy:
    build: ./proxy
    links:
      - projects
      - todos
      - client
      - file-server
    ports:
      - 1337:1337
      - 1447:1447
      - 1557:1557
      - 1667:1667
    restart: always
  redis-data:
    image: redis
    ports:
      - 6379