version: '2'
services:
  nginx:
    image: nginx:1-alpine
    links:
      - basket
      - recommendations
      - catalog
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./nginx/common:/usr/share/nginx/html/common
    ports:
      - "3000:3000"

  basket:
    build: ./basket
    links:
      - redis-data
    ports:
      - "3001:3001"
    volumes:
      - ./basket/src:/code/src

  recommendations:
    build: ./recommendations
    links:
      - redis-data
    ports:
      - "3002:3002"
    volumes:
      - ./recommendations/src:/code/src

  catalog:
    build: ./catalog
    links:
      - basket
      - recommendations
    ports:
      - "3003:3003"
    volumes:
      - ./catalog/src:/code/src

  redis-data:
    image: redis
    ports:
      - 6379