version: "3"

services:
  projects:
    build: ./projects
    links:
      - redis-data
    ports:
      - "1337:1337"
    volumes:
      - ./projects:/src:rw
  todos:
    build: ./todos
    links:
      - redis-data
    ports:
      - "1447:1447"
    volumes:
      - ./todos:/src:rw
  redis-data:
    image: redis
    ports:
      - 6379